=== kiko2004/ejercicios-tema-3/facturas.dtd
<!ELEMENT facturas (factura+)>
<!ELEMENT factura (numero, fecha, cliente, productos, resumen)>
<!ATTLIST factura id CDATA #REQUIRED>

<!ELEMENT numero (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

<!ELEMENT cliente (dni, nombre, direccion, codigo_postal, poblacion)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>

<!ELEMENT productos (producto+)>
<!ELEMENT producto (cantidad, descripcion, precio_unitario, iva)>
<!ATTLIST producto codigo CDATA #REQUIRED>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio_unitario (#PCDATA)>
<!ELEMENT iva (#PCDATA)>

<!ELEMENT resumen (forma_pago, descuento?)>
<!ELEMENT forma_pago (#PCDATA)>
<!ATTLIST forma_pago tipo (efectivo | tarjeta | cheque | transferencia) #REQUIRED>
<!ELEMENT descuento (#PCDATA)>

=== kiko2004/ejercicios-tema-3/Factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "facturas.dtd">
<facturas>
    <factura id="01">
        <numero>01</numero>
        <fecha>2021-10-23</fecha>
        <cliente>
            <dni>23572334A</dni>
            <nombre>Paco Molines</nombre>
            <direccion>Calle Sol/12</direccion>
            <codigo_postal>03740</codigo_postal>
            <poblacion>Gata de Gorgos</poblacion>
        </cliente>
        <productos>
            <producto codigo="01">
                <cantidad>2</cantidad>
                <descripcion>Ratón óptico</descripcion>
                <precio_unitario>100.00</precio_unitario>
                <iva>21</iva>
            </producto>
            <producto codigo="02">
                <cantidad>1</cantidad>
                <descripcion>Teclado mecánico</descripcion>
                <precio_unitario>80.00</precio_unitario>
                <iva>21</iva>
            </producto>
        </productos>
        <resumen>
            <forma_pago tipo="tarjeta">tarjeta</forma_pago>
            <descuento>10.00</descuento>
        </resumen>
    </factura>
    <factura id="02">
        <numero>02</numero>
        <fecha>2022-04-15</fecha>
        <cliente>
            <dni>87675621B</dni>
            <nombre>María Soler</nombre>
            <direccion>Calle Trossets/27</direccion>
            <codigo_postal>03740</codigo_postal>
            <poblacion>Gata de Gorgos</poblacion>
        </cliente>
        <productos>
            <producto codigo="03">
                <cantidad>5</cantidad>
                <descripcion>Auriculares Inalámbricos</descripcion>
                <precio_unitario>50.00</precio_unitario>
                <iva>21</iva>
            </producto>
            <producto codigo="04">
                <cantidad>2</cantidad>
                <descripcion>Impresora Láser</descripcion>
                <precio_unitario>160.00</precio_unitario>
                <iva>21</iva>
            </producto>
        </productos>
        <resumen>
            <forma_pago tipo="transferencia">transferencia</forma_pago>
        </resumen>
    </factura>
</facturas>
